- hosts: all
  user: pi
  sudo: true
  roles:
    - role: spk.ssh-secure
    - role: ryanlelek.sshd
    - role: mikolak.raspi-config
      raspi_config_update_packages: yes
      raspi_config_timezone: America/New_York
      raspi_config_locale: en_US.UTF8
      raspi_config_replace_user:
        name: zack
        path_to_ssh_key: "~/.ssh/id_rsa.pub"
    - role: nickjj.fail2ban
  tasks:
    - include: tasks/main.yml
  vars:
    fail2ban_services:
      - name: ssh
        port: ssh
        filter: sshd
        logpath: /var/log/auth.log
